### ISSUE TITLE
Incluir guia en este mismo repo

### ISSUE THREAD

**Issue by andresmoschini** [FromDoppler/UIChallenge#2]
Veo que en el readme hay un link a https://projects.invisionapp.com/d/main#/projects/prototypes/15530047  y se indica solicitar acceso a mmassimino@fromdoppler.com

¿Será posible incluir toda la información en este mismo repo para que cualquiera pueda participar con la menor burocracia posible?

**Comment by MarianaMS** [comment]
me encantaría, pero no, es una limitación de invison

**Comment by andresmoschini** [comment]
Gracias @MarianaMS, cuando puedas dame acceso y voy a intentar traducirlo en Markdown, HTML e imágenes para hacer un PR.

**Comment by andresmoschini** [comment]
Hablé con @MarianaMS, parece que el uso de invision es parte del scope del challenge. Cierro este issue.
